spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  recipient: ${EMAIL_RECIPIENT}

server:
  port: 8080

discord:
  token: ${DISCORD_TOKEN}
  channel-news-name: ${DISCORD_CHANNEL_NEWS_NAME}
  channel-reels-name: ${DISCORD_CHANNEL_REELS_NAME}
  channel-annotation-name: ${DISCORD_CHANNEL_ANNOTATION_NAME}

cron:
  cron-timer: ${CRON_TIMER}
gemini:
  token: ${GEMINI_TOKEN}